// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"auth/register":{"path":"auth/register","id":"auth/register"},"admin/index":{"path":"admin","id":"admin/index"},"forum/index":{"path":"forum","id":"forum/index"},"auth/login":{"path":"auth/login","id":"auth/login"},"forum/[id]":{"path":"forum/[id]","id":"forum/[id]"},"profile":{"path":"profile","id":"profile"},"_layout":{"path":"_layout","id":"_layout"},"index":{"path":"/","id":"index"},"test":{"path":"test","id":"test"},"ask":{"path":"ask","id":"ask"}} as const;
  return {
    routes,
    routeComponents: {
'auth/register': React.lazy(() => import(/* webpackChunkName: "src__pages__auth__register" */'../../../src/pages/auth/register.tsx')),
'admin/index': React.lazy(() => import(/* webpackChunkName: "src__pages__admin__index" */'../../../src/pages/admin/index.tsx')),
'forum/index': React.lazy(() => import(/* webpackChunkName: "src__pages__forum__index" */'../../../src/pages/forum/index.tsx')),
'auth/login': React.lazy(() => import(/* webpackChunkName: "src__pages__auth__login" */'../../../src/pages/auth/login.tsx')),
'forum/[id]': React.lazy(() => import(/* webpackChunkName: "src__pages__forum__id" */'../../../src/pages/forum/[id].tsx')),
'profile': React.lazy(() => import(/* webpackChunkName: "src__pages__profile" */'../../../src/pages/profile.tsx')),
'_layout': React.lazy(() => import(/* webpackChunkName: "src__pages___layout" */'../../../src/pages/_layout.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'test': React.lazy(() => import(/* webpackChunkName: "src__pages__test" */'../../../src/pages/test.tsx')),
'ask': React.lazy(() => import(/* webpackChunkName: "src__pages__ask" */'../../../src/pages/ask.tsx')),
},
  };
}
